### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Evanzsnr** [squareetlabs/ionic-rating-component#1]
Hello, when I add this component to my project and try to  build the project, I get the following error.

ERROR in node_modules/ionic-rating-component/dist/components/ionic-rating-component.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     set rating(val: number);
           ~~~~~~
node_modules/ionic-rating-component/dist/components/ionic-rating-component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get rating(): number;
           ~~~~~~

[ERROR] An error occurred while running subprocess ng.

**Comment by jcancig** [comment]
Thanks @Evanzsnr, sorry it took me so long to get back to you. The bug has been corrected

**Comment by Evanzsnr** [comment]
Okay, thanks
