### ISSUE TITLE
Implementing ionic-rating-component with IONIC5

### ISSUE THREAD

**Issue by jatinbphp** [squareetlabs/ionic-rating-component#8]
Is it possible to implement ionic-rating-component with IONIC-5.
As i have seen the implementation guide, where under title "Method 2 : Using @ViewChild and Observables" it uses import { Events } from '@ionic/angular' 
which("Events") is removed from IONIC-5 "@ionic/angular".

It is raising error when i use import { Events } from '@ionic/angular' statement in my .ts file.

**Comment by jcancig** [comment]
For Ionic 5 you must implement the method 1
